// main/ipc/registerBatchesIpc.js
// IPC handlers: `batches:get` / `batches:set` / `batches:generateExamples` /
// `batches:saveManualAs`. Storage is a separate JSON file alongside config.txt.
//
// R1.5b.4: AUDIT — none of the 4 handlers require a grantId. The
// legacy `pathUtils.isPathUnderAny` +
// `PathSecurityService.getAllowedRoots` gate is NOT used by any
// of these handlers (the audit verified the gates were never
// applied here — the handlers are all "internal" operations
// where the paths are either Main-known or user-picked via
// the native dialog):
//
//   - `batches:get`     — reads the persisted state from
//                         `configDir()/batches.json` (Main-known
//                         path, no renderer input).
//
//   - `batches:set`     — writes the persisted state to the same
//                         file (Main-known path). The `batches`
//                         arg is the full state object (no
//                         file-path strings).
//
//   - `batches:generateExamples` — writes 2 files
//                         (`example_batch_import.md` +
//                         `example_batch_import.txt`) to
//                         `cfgMod.effectiveOutputDir(cfg)`
//                         (Main-known path, derived from
//                         config). The `format` arg just picks
//                         which file to keep; no path
//                         strings in the payload.
//
//   - `batches:saveManualAs` — opens the native Save-As
//                         dialog; the user picks the file
//                         location explicitly. Per S1 §3, the
//                         dialog-EXPLICIT user gesture overrides
//                         the renderer-supplied path contract.
//                         The dest is user-picked (trust
//                         gesture).
//
// The legacy `pathSecurity.addTrusted(path.dirname(dest))` call
// inside `batches:saveManualAs` is a no-op for the new grant
// contract (the grant service is the source of truth for the
// R1.3 / R1.5a / R1.5b IPCs), but it IS load-bearing for the
// LEGACY allow-list still used by `registerPipelineIpc:82` (a
// not-yet-migrated IPC that uses `pathSecurity.getAllowedRoots()`
// as its gate). The call adds the dialog-picked folder to the
// legacy `trustedPickPaths` Set, which makes the picked folder
// accessible to subsequent legacy-gate operations (e.g.
// `pipeline:import` from a `pipeline:saveManualAs` dialog pick)
// without requiring the user to re-pick the folder. Removing
// the call would break the cross-IPC dialog-pick trust chain
// for any code path that still uses the legacy gate. Out of
// R1.5b.4 scope to refactor; the call is preserved as-is.

const { ipcMain, dialog } = require('electron');
const fs = require('fs');
const path = require('path');
const batchMod = require('../../src/batches');
const cfgMod = require('../../src/config');
const pathSecurity = require('../services/PathSecurityService');
// The AI-readable import manual is generated by a dedicated module so this IPC
// handler stays small + the manual is unit-testable.
const { generateManual, generateTxtManual } = require('../services/importDocManual');
// P1-A (360° Audit H-001): secure IPC wrapper.
const { secureHandle } = require('./secureHandle');

// The plain-text import manual. Extracted into a module-level function so both
// `batches:generateExamples` (writes to the output folder) and
// `batches:saveManualAs` (user-chosen location via Save-As dialog) share the
// same source of truth.
// H9-020: TXT manual is now rendered from the SAME capability registry as the
// Markdown manual (main/services/importDocManual.js), so the two formats can no
// longer drift. The old hand-coded template had already diverged (offered
// --upscale-multiplier 2/4 vs 2/3/4; advertised --genre/--bpm/--emotion which
// have no live executor consumer).
function buildTxtManual() { return generateTxtManual(); }

/**
 * @param {{ appRoot: string, getMainWindow: () => (Electron.BrowserWindow|null) }} deps
 */
function register(deps) {
  const getMainWindow = deps && typeof deps.getMainWindow === 'function' ? deps.getMainWindow : () => null;

  secureHandle('batches:get', { getMainWindow }, () => {
    // Return the proper default shape (object keyed by tab) on error, never
    // `[]`: the renderer's defensive reads happen not to crash on an empty
    // array, but any future code that spread state.batches would silently
    // produce junk keys. Matches batchMod.read's own error fallback.
    try { return batchMod.read(); }
    catch (e) { return batchMod.defaultBatches(); }
  });
  secureHandle('batches:set', { getMainWindow }, (_e, batches) => {
    try { batchMod.write(batches); return { ok: true }; }
    catch (e) { return { ok: false, error: String(e.message || e) }; }
  });

  secureHandle('batches:generateExamples', { getMainWindow }, async (_e, format) => {
    try {
      // Write the example files next to the user's actual generated assets
      // (the effective output dir), not inside the read-only asar archive.
      const cfg = cfgMod.read();
      const targetDir = cfgMod.effectiveOutputDir(cfg);
      try { fs.mkdirSync(targetDir, { recursive: true }); } catch (_) { /* best-effort */ }

      const mdContent = generateManual();
      const txtContent = buildTxtManual();

      fs.writeFileSync(path.join(targetDir, 'example_batch_import.md'), mdContent, 'utf8');
      fs.writeFileSync(path.join(targetDir, 'example_batch_import.txt'), txtContent, 'utf8');
      // Delete the format the user did NOT pick so they only see a single file.
      // Unknown / missing -> fall back to 'md'.
      const chosenFormat = (format === 'txt') ? 'txt' : 'md';
      let finalPath;
      if (chosenFormat === 'md') {
        try { fs.unlinkSync(path.join(targetDir, 'example_batch_import.txt')); } catch (_) { /* may not exist */ }
        finalPath = path.join(targetDir, 'example_batch_import.md');
      } else {
        try { fs.unlinkSync(path.join(targetDir, 'example_batch_import.md')); } catch (_) { /* may not exist */ }
        finalPath = path.join(targetDir, 'example_batch_import.txt');
      }
      return {
        ok: true,
        format: chosenFormat,
        path: finalPath,
        mdPath: path.join(targetDir, 'example_batch_import.md'),
        txtPath: path.join(targetDir, 'example_batch_import.txt'),
      };
    } catch (e) {
      return { ok: false, error: String(e.message || e) };
    }
  });

  // The import-doc button opens a native Save-As dialog so the user picks the
  // file name + location manually (instead of always writing into the
  // configured output folder). The chosen folder is trusted for the write.
  // `fmt` ('md' | 'txt', default 'md') selects the content + suggested name.
  secureHandle('batches:saveManualAs', { getMainWindow }, async (_e, fmt) => {
    try {
      const chosen = (fmt === 'txt') ? 'txt' : 'md';
      const win = getMainWindow();
      const cfg = cfgMod.read();
      // Default the dialog to the output folder + a sensible filename so the
      // user lands somewhere familiar, but they can navigate anywhere.
      const defaultName = chosen === 'txt' ? 'example_batch_import.txt' : 'example_batch_import.md';
      const defaultDir = cfgMod.effectiveOutputDir(cfg);
      const r = await dialog.showSaveDialog(win, {
        title: 'Save import instruction document',
        defaultPath: path.join(defaultDir, defaultName),
        filters: [
          { name: 'Markdown', extensions: ['md'] },
          { name: 'Text', extensions: ['txt'] },
          { name: 'All files', extensions: ['*'] },
        ],
      });
      if (r.canceled || !r.filePath) return { ok: false, canceled: true };
      const dest = r.filePath;
      // Determine the actual format from the chosen extension so a user who
      // picks the .txt filter but types a .md name (or vice-versa) still gets
      // content matching the extension they saved.
      const ext = path.extname(dest).toLowerCase();
      const useTxt = (ext === '.txt') || (chosen === 'txt' && ext !== '.md');
      const content = useTxt ? buildTxtManual() : generateManual();
      // Trust the destination's folder for the write (it lives outside the
      // output dir if the user navigated elsewhere).
      pathSecurity.addTrusted(path.dirname(dest));
      fs.writeFileSync(dest, content, 'utf8');
      return { ok: true, path: dest, format: useTxt ? 'txt' : 'md' };
    } catch (e) {
      return { ok: false, error: String(e.message || e) };
    }
  });
}

// generateManual now lives in main/services/importDocManual.js (re-exported so
// the existing module.exports contract and any direct callers keep working).
// buildTxtManual is exported so tests can assert on the plain-text template
// without regex-scraping the source (a regex scrape would break when the txt
// literal moves into a function).
module.exports = { register, generateManual, buildTxtManual };
