'use strict';

/**
 * Immutable encrypted secret blobs.
 * 
 * AUD-001/AUD-013 fix: Replace the old mutable/colliding/fallback SecretStore.
 * 
 * Important properties:
 * - The blob ID is generated by Main and never derived from a provider label.
 * - A stored blob is immutable. Replacement always creates a different ID.
 * - There is no machine-derived AES fallback.
 * - "Delete" means logical file removal; SSD wear levelling means physical
 *   secure erasure cannot be promised.
 * - Ordinary reads never perform garbage collection.
 */

const { app, safeStorage } = require('electron');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { CODES, AppError } = require('../errors/AppError');

const MAGIC = 'MMAS-SECRET';
const VERSION = 1;

/**
 * Get the root directory for secret storage.
 * @returns {string}
 */
function rootDir() {
  return path.join(app.getPath('userData'), 'secrets-v1');
}

/**
 * Create a new unique secret ID with a namespace prefix.
 * @param {string} namespace - Namespace prefix (e.g., 'minimax-primary', 'provider-openrouter')
 * @returns {string} Unique ID like 'minimax-primary-37c6f14e-4df8-40ac-bef8-a67b5ab5978e'
 * @throws {AppError} If namespace is invalid
 */
function createId(namespace) {
  if (!/^[a-z0-9-]{1,40}$/u.test(namespace)) {
    throw new AppError(CODES.INVALID_ARGUMENT, 'Invalid secret namespace.');
  }
  return `${namespace}-${crypto.randomUUID()}`;
}

/**
 * Get the file path for a secret ID.
 * @param {string} id - Secret ID
 * @returns {string} File path
 * @throws {AppError} If ID is invalid
 */
function fileFor(id) {
  if (!/^[a-z0-9-]{1,100}$/iu.test(id)) {
    throw new AppError(CODES.INVALID_ARGUMENT, 'Invalid secret identifier.');
  }
  return path.join(rootDir(), id + '.json');
}

/**
 * Require that secure storage is available.
 * @throws {AppError} If safeStorage is not available
 */
function requireStorage() {
  let available = false;
  try { available = safeStorage.isEncryptionAvailable(); } catch (_) {}
  if (!available) {
    throw new AppError(
      CODES.SECURE_STORAGE_UNAVAILABLE,
      'Secure credential storage is unavailable. Use session-only mode.'
    );
  }
}

/**
 * Write a new immutable secret blob.
 * @param {string} namespace - Namespace for the secret
 * @param {string} plaintext - The secret value
 * @returns {{id: string}} The new secret ID
 * @throws {AppError} On failure
 */
function writeNew(namespace, plaintext) {
  requireStorage();
  if (typeof plaintext !== 'string' || plaintext.length === 0) {
    throw new AppError(CODES.INVALID_ARGUMENT, 'Secret value is required.');
  }

  const id = createId(namespace);
  const dir = rootDir();
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  const finalPath = fileFor(id);
  const tempPath = finalPath + '.tmp-' + crypto.randomUUID();
  const encrypted = safeStorage.encryptString(plaintext);
  const envelope = JSON.stringify({
    magic: MAGIC,
    version: VERSION,
    id,
    ciphertext: encrypted.toString('base64'),
  });

  let fd;
  try {
    fd = fs.openSync(tempPath, 'wx', 0o600);
    fs.writeFileSync(fd, envelope, 'utf8');
    fs.fsyncSync(fd);
    fs.closeSync(fd);
    fd = undefined;
    fs.renameSync(tempPath, finalPath); // final name is a fresh UUID and cannot exist normally
    const verified = read(id);
    if (verified.value !== plaintext) {
      throw new AppError(CODES.SECRET_CORRUPT, 'Stored credential verification failed.');
    }
    return { id };
  } catch (error) {
    if (fd !== undefined) try { fs.closeSync(fd); } catch (_) {}
    try { fs.unlinkSync(tempPath); } catch (_) {}
    try { fs.unlinkSync(finalPath); } catch (_) {}
    if (error instanceof AppError) throw error;
    throw new AppError(CODES.SECRET_CORRUPT, 'Could not store the credential.', { cause: error });
  }
}

/**
 * Read a secret blob.
 * @param {string} id - Secret ID
 * @returns {{value: string}} The decrypted value
 * @throws {AppError} If not found, corrupt, or storage unavailable
 */
function read(id) {
  requireStorage();
  const target = fileFor(id);
  let raw;
  try {
    raw = fs.readFileSync(target, 'utf8');
  } catch (error) {
    if (error && error.code === 'ENOENT') {
      throw new AppError(CODES.SECRET_NOT_FOUND, 'Credential not found.');
    }
    throw new AppError(CODES.SECRET_CORRUPT, 'Credential could not be read.', { cause: error });
  }

  try {
    const envelope = JSON.parse(raw);
    if (envelope.magic !== MAGIC || envelope.version !== VERSION || envelope.id !== id) {
      throw new Error('invalid envelope');
    }
    const cipher = Buffer.from(envelope.ciphertext, 'base64');
    const value = safeStorage.decryptString(cipher);
    return { value };
  } catch (error) {
    throw new AppError(CODES.SECRET_CORRUPT, 'Credential data is corrupt or belongs to another account.', { cause: error });
  }
}

/**
 * Remove a secret blob.
 * @param {string} id - Secret ID
 * @returns {{removed: boolean}} Whether the secret was removed
 * @throws {AppError} On cleanup failure
 */
function remove(id) {
  const target = fileFor(id);
  try {
    fs.unlinkSync(target);
    return { removed: true };
  } catch (error) {
    if (error && error.code === 'ENOENT') return { removed: false };
    throw new AppError(CODES.SECRET_CORRUPT, 'Credential cleanup failed.', { cause: error });
  }
}

/**
 * Check if a secret exists.
 * @param {string} id - Secret ID
 * @returns {boolean}
 * @throws {AppError} On unexpected errors
 */
function exists(id) {
  try { read(id); return true; } catch (error) {
    if (error instanceof AppError && error.code === CODES.SECRET_NOT_FOUND) return false;
    throw error;
  }
}

module.exports = { writeNew, read, remove, exists, rootDir };
